# Generated by Django 5.1.15 on 2026-08-13 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relief', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=64, unique=True)),
                ('from_phone', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('channel', models.CharField(default='SMS', max_length=4)),
                ('accepted', models.BooleanField(default=False)),
                ('reply', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound', to='relief.reliefrequest')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_phone', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('language', models.CharField(default='en', max_length=8)),
                ('backend', models.CharField(default='mock', max_length=16)),
                ('delivered', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='relief.reliefrequest')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
