# Generated by Django 5.1.15 on 2026-08-13 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('hazard', models.CharField(choices=[('RIVERINE_FLOOD', 'Riverine Flood'), ('FLASH_FLOOD', 'Flash Flood'), ('CLOUDBURST', 'Cloudburst'), ('GLOF', 'Glof'), ('LANDSLIDE', 'Landslide'), ('CYCLONE', 'Cyclone'), ('STORM_SURGE', 'Storm Surge'), ('URBAN_FLOOD', 'Urban Flood'), ('HEATWAVE', 'Heatwave'), ('COLD_WAVE', 'Cold Wave'), ('DROUGHT', 'Drought'), ('EARTHQUAKE', 'Earthquake'), ('LIGHTNING', 'Lightning')], max_length=24)),
                ('severity', models.SmallIntegerField(default=3, help_text='1 (light) to 5 (severe)')),
                ('declared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('imd_warning_ref', models.CharField(blank=True, help_text='IMD or CWC bulletin reference', max_length=64)),
                ('districts', models.ManyToManyField(related_name='hazard_events', to='geo.district')),
            ],
            options={
                'ordering': ['-declared_at'],
            },
        ),
    ]
