# Generated by Django 5.1.15 on 2026-08-13 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('relief', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('label', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=16)),
                ('unit_weight_kg', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('boats_available', models.SmallIntegerField(default=0)),
                ('trucks_available', models.SmallIntegerField(default=0)),
                ('mules_available', models.SmallIntegerField(default=0)),
                ('has_heli_pad', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='geo.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_mode', models.CharField(choices=[('ROAD', 'ROAD'), ('BOAT', 'BOAT'), ('HELI', 'HELI'), ('MULE_PORTER', 'MULE_PORTER'), ('FOOT', 'FOOT')], max_length=16)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('EN_ROUTE', 'En route'), ('COMPLETED', 'Completed'), ('ABORTED', 'Aborted')], default='PLANNED', max_length=16)),
                ('trips_planned', models.SmallIntegerField(default=1)),
                ('payload_kg', models.FloatField(default=0)),
                ('distance_km', models.FloatField(default=0)),
                ('eta_hours', models.FloatField(default=0)),
                ('proof_reference', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatches', to='logistics.depot')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='relief.reliefrequest')),
            ],
            options={
                'verbose_name_plural': 'dispatches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='logistics.dispatch')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.resourcetype')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('reserved', models.FloatField(default=0)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='logistics.depot')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.resourcetype')),
            ],
            options={
                'unique_together': {('depot', 'resource')},
            },
        ),
    ]
