# Generated by Django 5.1.15 on 2026-08-13 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('hazards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReliefRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('IVR', 'Voice / IVR'), ('APP', 'Volunteer app'), ('WEB', 'Web form')], default='WEB', max_length=4)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('reporter_language', models.CharField(default='en', max_length=8)),
                ('needs', models.JSONField(default=list)),
                ('total_members', models.SmallIntegerField(default=1)),
                ('infants_under_2', models.SmallIntegerField(default=0)),
                ('children_2_to_12', models.SmallIntegerField(default=0)),
                ('pregnant_or_lactating', models.SmallIntegerField(default=0)),
                ('elderly_over_60', models.SmallIntegerField(default=0)),
                ('persons_with_disability', models.SmallIntegerField(default=0)),
                ('chronically_ill', models.SmallIntegerField(default=0)),
                ('livestock_count', models.SmallIntegerField(default=0)),
                ('has_pucca_house', models.BooleanField(default=True)),
                ('single_woman_headed', models.BooleanField(default=False)),
                ('road_status', models.CharField(choices=[('OPEN', 'Open'), ('SLOW', 'Slow'), ('BLOCKED', 'Blocked'), ('WASHED_OUT', 'Washed out')], default='OPEN', max_length=12)),
                ('water_depth_m', models.FloatField(default=0)),
                ('is_cut_off', models.BooleanField(default=False)),
                ('people_trapped', models.SmallIntegerField(default=0)),
                ('state', models.CharField(choices=[('REPORTED', 'Reported'), ('VERIFIED', 'Verified'), ('PRIORITISED', 'Prioritised'), ('ASSIGNED', 'Assigned'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed'), ('DUPLICATE', 'Duplicate'), ('ESCALATED', 'Escalated'), ('UNREACHABLE', 'Unreachable'), ('CANCELLED', 'Cancelled')], default='REPORTED', max_length=16)),
                ('priority', models.CharField(choices=[('RED', 'RED'), ('ORANGE', 'ORANGE'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN')], default='GREEN', max_length=8)),
                ('triage_score', models.FloatField(default=0)),
                ('sla_hours', models.SmallIntegerField(default=72)),
                ('access_mode', models.CharField(choices=[('ROAD', 'ROAD'), ('BOAT', 'BOAT'), ('HELI', 'HELI'), ('MULE_PORTER', 'MULE_PORTER'), ('FOOT', 'FOOT')], default='ROAD', max_length=16)),
                ('corroborating_reports', models.SmallIntegerField(default=0)),
                ('unreachable_attempts', models.SmallIntegerField(default=0)),
                ('verified_by_volunteer', models.BooleanField(default=False)),
                ('priority_overridden', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='relief.reliefrequest')),
                ('habitation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='geo.habitation')),
                ('hazard_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='hazards.hazardevent')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triage_score', 'reported_at'],
            },
        ),
        migrations.CreateModel(
            name='StateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=16)),
                ('to_state', models.CharField(max_length=16)),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='relief.reliefrequest')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TriageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('priority', models.CharField(max_length=8)),
                ('access_mode', models.CharField(max_length=16)),
                ('sla_hours', models.SmallIntegerField()),
                ('breakdown', models.JSONField(default=dict)),
                ('reasons', models.JSONField(default=list)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='relief.reliefrequest')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reliefrequest',
            index=models.Index(fields=['habitation', 'state', 'reported_at'], name='relief_reli_habitat_d6812a_idx'),
        ),
        migrations.AddIndex(
            model_name='reliefrequest',
            index=models.Index(fields=['state', '-triage_score'], name='relief_reli_state_012feb_idx'),
        ),
    ]
