# Generated by Django 5.1.15 on 2026-08-13 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('hazards', '0001_initial'),
        ('relief', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefrequest',
            name='deadline',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reliefrequest',
            index=models.Index(fields=['state', 'deadline'], name='relief_reli_state_dae882_idx'),
        ),
    ]
