# Generated by Django 5.1.15 on 2026-08-13 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('terrain', models.CharField(choices=[('HIMALAYAN', 'Himalayan'), ('NORTHEAST_HILLS', 'Northeast Hills'), ('GANGETIC_PLAIN', 'Gangetic Plain'), ('COASTAL', 'Coastal'), ('ISLAND', 'Island'), ('DESERT', 'Desert'), ('DECCAN_PLATEAU', 'Deccan Plateau'), ('URBAN_METRO', 'Urban Metro')], max_length=24)),
                ('river_basin', models.CharField(blank=True, max_length=64)),
                ('seismic_zone', models.SmallIntegerField(default=3)),
                ('population', models.IntegerField(default=0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('sdrf_helpline', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='geo.district')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='geo.state'),
        ),
        migrations.CreateModel(
            name='Habitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96)),
                ('code', models.CharField(help_text='Short code a citizen can type into an SMS, e.g. DBG012', max_length=12, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('households', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('elevation_m', models.FloatField(default=0)),
                ('is_flood_prone', models.BooleanField(default=False)),
                ('is_island_or_char', models.BooleanField(default=False)),
                ('has_heli_pad', models.BooleanField(default=False)),
                ('mobile_coverage', models.CharField(choices=[('4G', '4G'), ('2G', '2G'), ('NONE', 'No coverage')], default='4G', max_length=8)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitations', to='geo.block')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='geo_habitat_code_e36234_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'name')},
        ),
    ]
